Cat-MeetingのER図作成
Syousinn/my-cat-app pull request #3
Opened 2024-10-26 09:41 UTC by Syousinn

アプリCat-Meetingに関するER図を作成しました。下記にER図のスクリーンショットの画像、本サービスの概要、MVPで実装する予定の機能を記載しました。レビューよろしくお願い致します。

### ER図
[![Image from Gyazo](https://i.gyazo.com/66d76190d3eadf027f5a1985174b1273.png)](https://gyazo.com/66d76190d3eadf027f5a1985174b1273)

### 本サービスの概要

近所では捨て猫や野良猫が多く、食べ物や水分を摂れない猫がたくさんいます。
加入している保護猫活動のボランティアにも資金や人手に限界があり、多くの猫が亡くなるのを目の当たりにしてきました。
そんな悔しさと無念から、Cat-Meetingを制作しました。
Cat-Meetingは、飼い主と猫をマッチさせるアプリで、自分と相性の良い猫を見つける診断系サービスです。まず、ユーザーは会員登録やログインなしで、猫の毛色や大きさ、人懐っこさ、噛み癖など10個の質問に回答し、診断結果をすぐに確認できます。診断結果画面から、猫の写真と詳細情報を閲覧でき、お気に入り登録やxにシェアも可能です。
診断結果に満足できない場合や他の猫を探したい場合は、猫検索ページから条件を指定して猫を検索できます。猫の詳細ページでは、性格や去勢手術歴などの情報が表示されます。会員登録またはログインが必要ですが、レビュー機能もあり、他のユーザーの意見を参考にできます。
会員登録後はメインダッシュボードにアクセスし、猫の投稿、里親申請、コミュニティルーム、健康管理、専門家相談の機能が利用できます。
猫の投稿ページでは、発見した場所をGoogleマップから選び、詳細を入力して猫を投稿できます。
里親申請ページでは、登録された猫の情報を写真付きで確認でき、詳細に納得してから里親申請も行えます。
コミュニティルームでは、健康やしつけについてのチャットができ、さまざまな意見を交わすことが可能です。
健康管理機能では、ワクチン接種や健康診断の日程のLINE通知設定が可能です。また、専門家への相談も簡単にできるため、飼い主の不安を解消するサポートが充実しています。

### MVPで実装する予定の機能

- [✔] トップページ
- [✔] ユーザー登録機能
- [✔] ログイン機能
- [✔] 質問に基づくマッチング機能
- [✔] 猫の一覧ページ閲覧機能
- [✔] 猫の詳細ページ閲覧機能
- [✔] 写真投稿機能
- [✔] 掲示板（猫）投稿機能
- [✔] 掲示板（猫）編集機能
- [✔] 掲示板（猫）削除機能
- [✔] 条件に合う猫検索機能

### ER図の注意点

- [✔] プルリクエストに最新のER図のスクリーンショットを画像が表示される形で掲載できているか？
- [✔] テーブル名は複数形になっているか？
- [✔] カラムの型は記載されているか？
- [✔] 外部キーは適切に設けられているか？
- [✔] リレーションは適切に描かれているか？多対多の関係は存在しないか？
- [✔] カラムの型は記載されているか？
- [✔] STIは使用しないER図になっているか？
- [✔] Postsテーブルにpoast_nameのように"テーブル名+カラム名"を付けていないか？

2024-10-27 07:38 UTC, tarakish requested changes
確認しました。以下コメントです！

---

- Users
  - 外部認証は現状1種類のみ利用する予定でしょうか？
    - 複数利用する場合はuidとproviderを別テーブルに切り出すと良さそうです

- Health_records
  - 〇〇_typeという名前のカラムはポリモーフィック関連付け用として使うことが望ましいので、もしそうでなければ別の名前が良いかと思います。
  - こちらのテーブルとカラムの役割についてご説明いただけますか？

- Community_rooms
  - どのテーブルとも関連付けがありませんが、メッセージなどはどのように送受信するイメージでしょうか？

2024-10-28 12:20 UTC, Syousinn commented
ご指摘ありがとうございます。以下に具体的な変更内容と最新のER図のスクリーンショットを掲載いたします。

ER図

[![Image from Gyazo](https://i.gyazo.com/961e0f68facc3c5855d660973d2200dc.png)](https://gyazo.com/961e0f68facc3c5855d660973d2200dc)

変更内容
1. Usersテーブルの変更について
将来的に複数の外部認証を利用する可能性があるため、usersテーブルに記載していたuidカラムとproviderカラムを新しく作成したAuthenticationProvidersテーブルに移しました。これにより、将来的な拡張をしやすくしました。

2. Health_recordsテーブルの変更について
Health_recordsテーブルにおけるカラム名を見直し、health_record_categoryという名称に変更しました。また、ポリモーフィック関連付けを行っていないため、以下の新しいカラムを追加しました。

1....health_record_category: 健康記録のカテゴリ（String）　ワクチンや健康診断など、健康記録の種類を示すカラムです。
2....vaccine_name: ワクチンの名前（string）　接種したワクチンの名前を保存するカラムです。
3....next_vaccine_due: 次回のワクチン接種予定日（datetime）次回のワクチン接種の予定日を保存するカラムです。
4....checkup_results: 健康診断の結果（text）　　健康診断の結果を保存するカラムです。
5....next_checkup_due: 次回の健康診断予定日（datetime）次回の健康診断の予定日を保存するカラムです。
6....description: 具体的な説明（text）健康記録に関するその他の詳細情報を保存するためのカラムです。

Health_recordsテーブルは、個々の健康記録を管理するためのテーブルとして設計しました。具体的には、ワクチン接種や健康診断の結果、予定など、健康に関する情報を保存します。

3. Community_roomsテーブルのメッセージ送受信について
Community_roomsテーブルは、ユーザーが猫に関する話題をチャット形式で共有するための部屋を表しています。メッセージの送受信を行うために、Messagesテーブルを新しく設け、以下のカラムを追加しました。
1....id: 主キー（integer）
2....community_room_id: どのコミュニティールームに属するかを示す外部キー（integer）
3....user_id: メッセージを送信したユーザーのID（integer）
4....content: メッセージの内容（Text）
5....created_at: 作成日時（datetime）
6....updated_at: 更新日時（datetime）

ご確認いただき、他にアドバイスやご意見があれば、ご指摘よろしくお願いします。

2024-10-29 04:08 UTC, tmtkzk0823 commented
ご説明ありがとうございます。
以下、追加のコメントです。

---

### Health_recordsテーブル
こちらのテーブルは「ユーザーの健康を管理する」テーブルの認識であっていますでしょうか？
ユーザーのみと紐づいていますが、カラムを見るとワクチンや健康診断など猫に関わってきそうなカラムがあるため確認させてください。

2024-10-29 05:39 UTC, Syousinn commented
レビューありがとうございます。ご指摘の内容について確認させていただきました。下記に最新のER図と変更内容を記載します。

ER図

[![Image from Gyazo](https://i.gyazo.com/8dd4953cbb74e352cb0e946f42094ff7.png)](https://gyazo.com/8dd4953cbb74e352cb0e946f42094ff7)

変更内容

Health_recordsテーブルは、猫の健康を管理するためのテーブルとして認識していましたが、Catsテーブルとのリレーションを定義できていませんでした。また、Health_recordsという名称が、ユーザー自身の健康状態に関するテーブルと誤解される可能性があることも理解しました。
ご指摘を受けて、テーブル名をCat_health_recordsに変更しました。これにより、テーブルの目的がより明確になったと思います。また、Cat_health_recordsテーブルにFKとしてcat_id: Integerを追加し、belongs_to :catのリレーションを定義しました。これにより、猫の健康記録と猫自身をしっかり関連付けしました。

今後もレビューを参考にしながら、改善に努めていきます。
他にアドバイスやご意見があれば、ご指導よろしくお願いします。

2024-10-29 12:13 UTC, Tsuchiya2 commented
概ね良いかと思います。LGTMです。
修正が必要になった際は適宜修正して開発を進めましょう。

2024-10-30 10:56 UTC, merged